runmode: debug # debug, release, test
port: :8080
name: blog
url: http://127.0.0.1:8080
database:
  name: blog
  url: 127.0.0.1:3306
  username: root
  password: 
  params: charset=utf8&parseTime=True&loc=Asia/Shanghai
mysqllog: true
jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
# 阿里云
uploadUrl: http://gilgamesh.oss-cn-hongkong.aliyuncs.com
accessKeyId:
accessKeySecret:
bucketName: gilgamesh